USER_APP_OBJS = output/userApp/main.o output/userApp/init.o

output/userApp/init.o: userApp/init.c
	gcc -c ${C_FLAGS} userApp/init.c -o output/userApp/init.o

output/userApp/main.o: userApp/main.c
	gcc -c ${C_FLAGS} userApp/main.c -o output/userApp/main.o
